{
    'name': 'Silver Product',
    'version': '19.0.1.0.0',
    'license': 'LGPL-3',
    'summary': 'Customizations for product views',
    'author': 'SilverData',
    'website': 'https://www.silverdata.org',
    'category': 'Sales',
    'depends': ['product', 'stock', 'silver_network', 'silver_base', 'crm'],
    'data': [
        'security/ir.model.access.csv',
        'views/product_view.xml',
        'views/stock_production_lot_views.xml',
        'views/stock_lot_views.xml',
        'views/silver_core_views.xml',
        'views/silver_ap_views.xml',
        'views/silver_olt_views.xml',
        'views/silver_onu_profile_views.xml',
        'views/silver_hardware_model_views.xml',
    #    'views/silver_olt_card_port_views.xml',
#        'views/silver_radius_views.xml',
        'views/product_brand_views.xml',
        'views/product_view_invisible.xml',
        'views/menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'silver_product/static/src/css/stock_lot.css',
        ],
    },
    'installable': True,
    'application': False,
}
