{
    'name': 'Silver Product',
    'version': '17.0.1.0.0',
    'summary': 'Customizations for product views',
    'author': 'SilverData',
    'website': 'https://www.silverdata.org',
    'category': 'Sales',
    'depends': ['product', 'stock', 'silver_network'],
    'data': [
        'security/ir.model.access.csv',
        'views/product_view.xml',
        'views/stock_production_lot_views.xml',
        'views/silver_core_views.xml',
        'views/silver_ap_views.xml',
        'views/silver_box_views.xml',
        'views/silver_olt_views.xml',
        'views/silver_olt_card_port_views.xml',
        'views/menus.xml',
        'views/product_brand_views.xml',
    ],
    'installable': True,
    'application': False,
}
