{
    'name': "Infrastructura",
    'summary': "Módulo para la gestión de proveedores de servicios de Internet (ISP)",
    'description': """
        Este módulo proporciona las herramientas necesarias para gestionar la infraestructura de red de un ISP,
        incluyendo nodos, equipos core, OLTs, y más.
       
    """,
    'author': "Silverdale",
    'website': "https://www.silverdale.com",
    'category': 'Industries',
    'version': '17.0.2.1',
    'depends': ['base', 'mail', 'stock', 'product', 'account'],
    'data': [
        'views/isp_views.xml',

        'security/ir.model.access.csv',
        'views/isp_node_views.xml',
        'views/isp_core_views.xml',
        'views/isp_olt_views.xml',
        'views/isp_olt_card_views.xml',
        'views/isp_olt_card_port_views.xml',
        'views/isp_splitter_views.xml',
        'views/isp_router_views.xml',
        'views/isp_router_wizards_views.xml',
        'views/isp_box_views.xml',
        'views/isp_ap_views.xml',
        'views/isp_radius_views.xml',
        'views/isp_radius_wizards_views.xml',
        'views/isp_splice_closure_views.xml',
        'views/isp_cable_views.xml',
        'views/product_brand_views.xml',
        'views/isp_device_networks_views.xml',
        'views/isp_kex_algorithms_views.xml',
        'views/isp_vlan_views.xml',
        'views/addres_list_channel_line_views.xml',
        'views/isp_ip_address_line_views.xml',
        'views/isp_ip_address_views.xml',
        'views/isp_core_port_line_views.xml',
        'views/olt_line_product_views.xml',
        'views/isp_olt_users_views.xml',
        'views/isp_tr_069_views.xml',
        'views/isp_onu_line_views.xml',
        'views/device_pool_ip_views.xml',
        'views/isp_radius_line_views.xml',
        "views/isp_menus.xml",
    ],
    'assets': {
        'web.assets_backend': [
            'silver_isp/static/src/js/raphael.min.js',
            'silver_isp/static/src/js/ppp_speed_chart.js',
            'silver_isp/static/src/xml/ppp_speed_chart.xml',
                'silver_isp/static/src/css/general.css',
        ],
    },
    'installable': True,
    'application': True,
}