{
    'name': "Silver ISP",
    'summary': "Módulo para la gestión de proveedores de servicios de Internet (ISP)",
    'description': """
        Este módulo proporciona las herramientas necesarias para gestionar la infraestructura de red de un ISP,
        incluyendo nodos, equipos core, OLTs, y más.
    """,
    'author': "Silverdale",
    'website': "https://www.silverdale.com",
    'category': 'Industries',
    'version': '17.0.1.0.0',
    'depends': ['base', 'mail', 'stock', 'product', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'views/isp_node_views.xml',
        'views/isp_core_views.xml',
        'views/isp_olt_views.xml',
        'views/isp_olt_card_views.xml',
        'views/isp_olt_card_port_views.xml',
        'views/isp_splitter_views.xml',
        'views/isp_router_views.xml',
        'views/isp_router_wizards_views.xml',
        'views/isp_box_views.xml',
        'views/isp_ap_views.xml',
        'views/isp_radius_views.xml',
        'views/isp_views.xml',
    ],
    'installable': True,
    'application': True,
}