{
    'name': "Infraestructura",
    'summary': "Módulo para la gestión de proveedores de servicios de Internet (Silver)",
    'description': """
        Este módulo proporciona las herramientas necesarias para gestionar la infraestructura de red de un Silver,
        incluyendo nodos, equipos core, OLTs, y más.
       
    """,
    'author': "Silverdale",
    'website': "https://www.silverdale.com",
    'category': 'Industries',
    'version': '17.0.2.1',
    'depends': ['base', 'mail', 'stock', 'account', 'silver_base'],
    'data': [
        'views/silver_views.xml',

        'security/ir.model.access.csv',
        'views/silver_zone_views.xml',
        'views/silver_node_views.xml',
        'views/silver_core_views.xml',
        'wizards/silver_netdev_system_info_wizard_view.xml',
        'views/silver_olt_views.xml',
        'views/silver_olt_card_views.xml',
        'views/silver_olt_card_port_views.xml',
        'views/silver_splitter_views.xml',
        'views/silver_post_views.xml',
        'views/silver_router_views.xml',
        'views/silver_router_wizards_views.xml',
        'views/silver_box_views.xml',
        'views/silver_ap_views.xml',
        'views/silver_radius_views.xml',
        'views/silver_radius_wizards_views.xml',
        'views/silver_splice_closure_views.xml',
        'views/silver_cable_views.xml',
        'views/silver_device_networks_views.xml',
        'views/silver_kex_algorithms_views.xml',
        'views/silver_vlan_views.xml',
        'views/address_list_channel_line_views.xml',
        'views/silver_ip_address_pool_views.xml',
        'views/silver_ip_address_views.xml',
        'views/silver_core_port_line_views.xml',
        'views/olt_line_product_views.xml',
        'views/silver_olt_users_views.xml',
        'views/silver_tr_069_views.xml',
        'views/silver_onu_line_views.xml',
        'views/silver_device_pool_ip_views.xml',
        'views/silver_radius_line_views.xml',
        'views/silver_radius_user_views.xml',
        "views/menus.xml",
    ],
    'assets': {
        'web.assets_backend': [
            'silver_base/static/src/css/general.css',
            'silver_network/static/src/js/raphael.min.js',
            'silver_network/static/src/js/ppp_speed_chart.js',
            'silver_network/static/src/js/ppp_line_speed_chart.js',
            'silver_network/static/src/js/m2o_widget.js',
            'silver_network/static/src/js/ip_widget.js',
            'silver_network/static/src/js/node_map_widget.js',
            'silver_network/static/src/js/node_network_widget.js',
            'silver_network/static/src/js/system_info_chart_widget.js',
            'silver_network/static/src/js/realtime_speed_widget.js',
            'silver_network/static/src/xml/interface_speed_updater.xml',
            'silver_network/static/src/js/interface_speed_updater.js',
            'silver_network/static/src/js/interface_list_view.js',
        #],
        #'web.assets_qweb': [
            'silver_network/static/src/xml/ppp_speed_chart.xml',
            'silver_network/static/src/xml/system_info_chart_widget.xml',
            'silver_network/static/src/xml/ppp_line_speed_chart.xml',
            'silver_network/static/src/xml/node_map_widget.xml',
            'silver_network/static/src/xml/node_network_widget.xml',
        ],
    },
    'installable': True,
    'application': True,
}
