{
    'name': 'Silver Contract',
    'version': '17.0.1.0.0',
    'icon': 'static/description/icon.png',
    'summary': 'Módulo de Contratos para ISP',
    'description': """
        Gestión de contratos de servicios de Internet, incluyendo clientes,
        planes, equipos y facturación recurrente.
    """,
    'author': 'Gemini',
    'website': 'https://www.google.com',
    'category': 'Services/ISP',
    'depends': ['base',   'silver_base'],
    'data': [
        'security/ir.model.access.csv',
        'views/silver_contract_views.xml',
        'views/silver_payment_type_views.xml',
        'views/silver_service_type_views.xml',
        'views/silver_plan_type_views.xml',
        'views/silver_contract_term_views.xml',
        'views/silver_cutoff_date_views.xml',
        'views/silver_cutoff_factor_views.xml',
        'views/contract_days_cutoff_line_views.xml',
        'views/contract_template_wp_views.xml',
        'views/silver_discount_plan_views.xml',
        'views/silver_contract_holding_views.xml',
        'views/silver_reception_channel_views.xml',
        'views/silver_contract_tag_views.xml',
        'views/silver_ip_pool_views.xml',
        'views/silver_wifi_channel_line_views.xml',
        'views/menus.xml',
    ],
    'demo': [
        'demo/demo_data.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
